### ISSUE TITLE
[增强]增加选谱界面滚轮滑动速度

### ISSUE THREAD

**Issue by oritong** [BlophyNova/BlophyNovaEdit#1]
https://github.com/user-attachments/assets/1ee5ac99-78ca-47c5-a111-9c71b097a081

**Comment by HuaWaterED** [comment]
在修了在修了qwq

**Comment by HuaWaterED** [comment]
[https://github.com/BlophyNova/BlophyNovaEdit/commit/b88bd357ab00f2f6c3cbca58dcc6ed25123c1042](url)

已修
