### ISSUE TITLE
[新功能请求&BUG修复]ctrl+左键

### ISSUE THREAD

**Issue by oritong** [BlophyNova/BlophyNovaEdit#3]
现版本ctrl+左键不会显示选取音符的框

https://github.com/user-attachments/assets/c85b96e6-927b-49ef-bbec-cc64b9e93e6e

新功能请求：
ctrl+左键能选取多个事件/音符便于全部复制（包括跨框）
类似

https://github.com/user-attachments/assets/c9a03212-4d79-44cd-ae55-0eacf3f5cfd1

**Comment by HuaWaterED** [comment]
Ctrl+左键会出现选择框，如果事件的四角其中一角在框的范围内会选中
已加入todolist
