### ISSUE TITLE
[BUG修复]创建谱面后出现多个谱面

### ISSUE THREAD

**Issue by oritong** [BlophyNova/BlophyNovaEdit#4]
盲猜是因为多难度问题，可能吧

https://github.com/user-attachments/assets/21c1d92e-5900-4cee-b405-78fb96f87251

**Comment by oritong** [comment]
哦对，重启后多的就没了

**Comment by HuaWaterED** [comment]
已加入todolist

**Comment by HuaWaterED** [comment]
https://github.com/BlophyNova/BlophyNovaEdit/commit/82e327a78539e673c8bab7864c8949af22cc0aa8
