### ISSUE TITLE
[新功能请求]区分多难度谱面&创建多难度谱面

### ISSUE THREAD

**Issue by oritong** [BlophyNova/BlophyNovaEdit#5]
尝试复制谱面最后无效
![image](https://github.com/user-attachments/assets/dcfdf7d2-581e-4858-96c5-e0501c1989fd)
![image](https://github.com/user-attachments/assets/3de01752-c4bd-4b46-bd89-4bbf6d06b77d)
![image](https://github.com/user-attachments/assets/2ea2b452-f8c7-4c0e-93dc-5a831cddbde3)
不过这个不急（

**Comment by HuaWaterED** [comment]
已加入todolist

**Comment by HuaWaterED** [comment]
已修：https://github.com/BlophyNova/BlophyNovaEdit/commit/82e327a78539e673c8bab7864c8949af22cc0aa8
